apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: taloshd.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: talos-hetnzer-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: robot-provider-secret
      key: credentials
